apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: ingress-nginx
  annotations:
    ingress.kubernetes.io/class: nginx
    ingress.kubernetes.io/enable-cors: "true"
    ingress.kubernetes.io/cors-allow-methods: "GET, POST"
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/service-upstream: "true"
    ingress.kubernetes.io/http-snippet: |
        set $allow_ip $remote_addr;
        if ($http_x_forwarded_for ~ "^(\d+\.\d+\.\d+\.\d+)") {
          set $allow_ip $1;
        }
        # geo $allow_ip $geo {
        #   default        0;
        #   10.1.0.0/16    1;
        # }
    # ingress.kubernetes.io/configuration-snippet: |
    #     if($geo) {
    #       return 302 /tea;
    #     }



spec:
  spec:
  rules:
  - http:
      paths:
      - path: /tea
        backend:
          serviceName: tea-svc
          servicePort: 80
      - path: /coffee
        backend:
          serviceName: coffee-svc
          servicePort: 80

